databases:
- name: mattermost
  plan: free

services:
- type: web
  name: mattermost
  env: docker
  plan: free
  dockerfilePath: ./app/Dockerfile
  dockerContext: ./app
  autoDeploy: false
  disk:
    name: config
    mountPath: /mattermost/config
    sizeGB: 1
  envVars:
  - key: MM_USERNAME
    fromDatabase:
      name: mattermost
      property: user
  - key: MM_PASSWORD
    fromDatabase:
      name: mattermost
      property: password
  - key: MM_DBNAME
    fromDatabase:
      name: mattermost
      property: database
